name: self-hosted-windows-checkout-test

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true    
      - name: windows
        uses: actions/checkout@vmjoseph/toolkit-windows-exec
        with:
          fetch-depth: 0
          clean: true
