name: hosted-linux-checkout-test

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: windows
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          clean: true
