name: self-hosted-windows-checkout-test

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  basic:
    runs-on: self-hosted
    name: windows
    steps:
    - uses: actions/checkout@vmjoseph/toolkit-windows-exec
      with:
        fetch-depth: 0
        clean: true
